frontend:
  image: '/frontend:'
  replicas: 1
  service:
    type: ClusterIP
  ingress:
    enabled: true
    host: dev-frontend.local
backend:
  image: '/backend:'
  replicas: 1
  service:
    type: ClusterIP
  ingress:
    enabled: true
    host: dev-backend.local
  env:
    MONGO_URL: mongodb://mongodb-0.mongodb.default.svc.cluster.local:27017
mongodb:
  image: '/mongodb:'
  replicas: 1
  storage: 512Mi
