name: GitOps Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - test
      - main

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    env:
      VERSION: v1.0.${{ github.run_number }}
      DOCKER_NAMESPACE: manishshukla
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Pull, tag, and push images
        run: |
          docker pull nginx:latest
          docker tag nginx:latest $DOCKER_NAMESPACE/frontend:$VERSION
          docker push $DOCKER_NAMESPACE/frontend:$VERSION

          docker pull node:18
          docker tag node:18 $DOCKER_NAMESPACE/backend:$VERSION
          docker push $DOCKER_NAMESPACE/backend:$VERSION

          docker pull mongo:6.0
          docker tag mongo:6.0 $DOCKER_NAMESPACE/mongodb:$VERSION
          docker push $DOCKER_NAMESPACE/mongodb:$VERSION

  update-values:
    runs-on: ubuntu-latest
    needs: build-and-push-images
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq

      - name: Determine environment and update values.yam
        run: |
            if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
              VALUES_FILE="values/prod/values.yaml"
            else
              VALUES_FILE="values/dev/values.yaml"
            fi

            yq -i '.frontend.image = "${{ env.DOCKER_NAMESPACE }}/frontend:${{ env.VERSION }}"' $VALUES_FILE
            yq -i '.backend.image = "${{ env.DOCKER_NAMESPACE }}/backend:${{ env.VERSION }}"' $VALUES_FILE
            yq -i '.mongodb.image = "${{ env.DOCKER_NAMESPACE }}/mongodb:${{ env.VERSION }}"' $VALUES_FILE

      - name: Commit and push changes
        run: |
          git config user.name "GitOps Bot"
          git config user.email "gitops@example.com"
          git add values.yaml
          git commit -m "Update image tags to $VERSION"
          git push

